
######################################## DEVELOP ###############################################



redowise-app-build:
  image: docker:24.0.5
  variables:
    TAG_COMMIT: "$CI_REGISTRY_IMAGE/redowise:latest"
  stage: build
  services:
    - name: docker:24.0.5-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build  -t "$TAG_COMMIT" .
    - docker push "$TAG_COMMIT"
  only:
    - main



redowise-app-deploy:
  image: docker:24.0.5
  variables:
    SSH: $PRODUCTION_SSH_PATH
    DEPLOY_PATH: '/home/deployer/projects/redowise'
    TAG_COMMIT: "$CI_REGISTRY_IMAGE/redowise:latest"
    
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY_PRODUCTION")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - |
      ssh $SSH -p 1998 "
        cd $DEPLOY_PATH
        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
        docker-compose pull && docker-compose down
        docker-compose up -d
        docker system prune -a --force"

  only:
    - main




